{
 "title": "Dramatiq",
 "description": "A dashboard for Dramatiq, a distributed task processing library for Python.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Messages in progress",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dramatiq_messages_inprogress)"
    }
   ]
  },
  {
   "title": "Delayed messages in progress",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dramatiq_delayed_messages_inprogress)"
    }
   ]
  },
  {
   "title": "Total messages processed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dramatiq_messages_total)" }
   ]
  },
  {
   "title": "Average processing rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dramatiq_messages_total[5m]))"
    }
   ]
  },
  {
   "title": "Message processing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(dramatiq_message_duration_milliseconds_sum[5m]) / irate(dramatiq_message_duration_milliseconds_count[5m])",
     "legendFormat": "{{actor_name}}({{queue_name}}) avg duration"
    },
    {
     "expr": "irate(dramatiq_messages_total[5m])",
     "legendFormat": "{{actor_name}}({{queue_name}}) processed"
    }
   ]
  },
  {
   "title": "Message retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(dramatiq_message_retries_total[5m])",
     "legendFormat": "{{actor_name}}({{queue_name}}) retried"
    },
    {
     "expr": "irate(dramatiq_message_rejects_total[5m])",
     "legendFormat": "{{actor_name}}({{queue_name}}) failed"
    }
   ]
  },
  {
   "title": "Message duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dramatiq_message_duration_milliseconds_bucket[5m])) by (actor_name, queue_name, le)) ",
     "legendFormat": "{{actor_name}}({{queue_name}}) p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dramatiq_message_duration_milliseconds_bucket[5m])) by (actor_name, queue_name, le)) ",
     "legendFormat": "{{actor_name}}({{queue_name}}) p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(dramatiq_message_duration_milliseconds_bucket[5m])) by (actor_name, queue_name, le)) ",
     "legendFormat": "{{actor_name}}({{queue_name}}) p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dramatiq_message_duration_milliseconds_bucket[5m])) by (actor_name, queue_name, le)) ",
     "legendFormat": "{{actor_name}}({{queue_name}}) p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(dramatiq_message_duration_milliseconds_bucket[5m])) by (actor_name, queue_name, le)) ",
     "legendFormat": "{{actor_name}}({{queue_name}}) p25"
    }
   ]
  }
 ]
}